baseURL = 'https://stonenet.org/'
languageCode = 'en-us'
title = 'Stonenet'
theme = 'risotto'
sectionPagesMenu = 'main'



[menu]
[[menu.main]]
  name = 'Download'
  url = '/download'
  weight = 1
[[menu.main]]
  name = 'Info'
  url = '/info'
  weight = 2

